# Generated by Django 4.1.7 on 2023-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_on'], 'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
